### ISSUE TITLE
viewport margin

### ISSUE THREAD

**Issue by Sjoerd** [cnu4/vue-codemirror-lite#16]
Hello,
I'm trying to set the viewport margin to [Infinity](https://codemirror.net/demo/resize.html), but it doesn't work.

```
<codemirror :options="{
          tabSize: 2,
          viewportMargin: Infinity,
          lineNumbers: true,
          mode: this.mode,
          line: true,
        }" />
```

**Comment by cnu4** [comment]
Have you set the editor's height style to auto?
```css
.CodeMirror {
  height: auto;
}
```

**Comment by Sjoerd** [comment]
Yes, I have.

**Comment by cnu4** [comment]
Sorry for taking so long to reply.

You need to defind a CSS rules with higher specificity to override the default style

```css
.CodeMirror {
  height: 300px;
}
```

If you run demo in this repository，rules as shown below will work

```css
.cm-container .CodeMirror {
  height: auto;
}
```
